name = "portfolio"
pages_build_output_dir = "dist"
compatibility_date = "2026-01-01"

[[kv_namespaces]]
binding = "PORTFOLIO_KV"
id = "3aba7a1e49d5444fb8e9abab175f6ed2"

[[r2_buckets]]
binding = "PORTFOLIO_BUCKET"
bucket_name = "portfolio-files"

[vars]
PUBLIC_BUCKET_URL = "https://pub-ff689358cae24e9e985d57ad4fe797ff.r2.dev"
ADMIN_USERNAME = "nikhiladmin"
